version: '3.8'
services:
  db:
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_DB: 'imdb'
      POSTGRES_USER: 'spring'
      POSTGRES_PASSWORD: 'spring'
    ports:
      - '5435:5432'
  test-db:
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_DB: 'imdb-test'
      POSTGRES_USER: 'springtest'
      POSTGRES_PASSWORD: 'springtest'
    ports:
      - '12222:5432'